version: "3"
services:
    imagens:
      container_name: imagens
      image: imagens #tonanuvem/imagens-chat
      ports:
        - "8081:8081"
      #environment: só pega via command
      #  - "QUARKUS_DYNAMODB_ENDPOINT-OVERRIDE=http://localhost:8000"
      #  - "QUARKUS_DYNAMODB_AWS_REGION=us-east-1"
      #  - "QUARKUS_DYNAMODB_AWS_CREDENTIALS_TYPE=static"
      #  - "QUARKUS_DYNAMODB_AWS_CREDENTIALS_STATIC-PROVIDER_ACCESS-KEY-ID=test-key"
      #  - "QUARKUS_DYNAMODB_AWS_CREDENTIALS_STATIC-PROVIDER_SECRET-ACCESS-KEY=test-secret"
      entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
      command: |
               /bin/bash -c "
                 echo executando entrypoint manual
                 aws --version
                 aws configure set aws_access_key_id test-key
                 aws configure set aws_secret_access_key test-secret
                 cat /.aws/credentials
                 echo Waiting for DynamoDB service start...;
                 while ! nc -z dynamodb 8000; do
                   echo .
                   sleep 5
                 done
                 echo DynamoDB Connected!;
                 aws dynamodb create-table --table-name ImagensDB --endpoint-url http://dynamodb:8000  --attribute-definitions AttributeName=idName,AttributeType=S --key-schema AttributeName=idName,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
                 aws dynamodb list-tables --endpoint-url http://dynamodb:8000
                 java -Dquarkus.http.host=0.0.0.0 -Dquarkus.dynamodb.endpoint-override=http://dynamodb:8000 -Dquarkus.dynamodb.aws.region=us-east-1 -Dquarkus.dynamodb.aws.credentials.type=static -Dquarkus.dynamodb.aws.credentials.static-provider.access-key-id=test-key -Dquarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test-secret -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
               "
    dynamodb:
      container_name: dynamodb
      image: amazon/dynamodb-local:latest
      ports:
        - "8000:8000"
      volumes:
        - ./volumes/dynamodb:/data/
      environment:
        AWS_ACCESS_KEY_ID: test-key
        AWS_SECRET_ACCESS_KEY: test-secret
        AWS_REGION: us-east-1
      entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
      command: |
               /bin/bash -c "
                 echo executando entrypoint manual
                 java -jar DynamoDBLocal.jar -sharedDb
               "
